[package]
name = "kc-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
ed25519-dalek.workspace = true
kc-api-types = { path = "../kc-api-types" }
rand.workspace = true
sha2.workspace = true
